codecov:
  notify:
    require_ci_to_pass: yes
    # wait for unit and integration test builds.
    after_n_builds: 2
  strict_yaml_branch: master  # only use the latest copy on master branch

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        enabled: yes
        target: 79%  # This needs to be updated to 85 or higher.
    patch:
      default:
        enabled: yes
        target: 95%
